version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Status: Review Needed"
      - "Type: Dependencies"
      - "Type: Maintenance"
      - "Type: CI"
      - "Type: Meta"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      types:
        patterns:
          - "@types*"
      eslint:
        patterns:
          - "*eslint*"
    labels:
      - "Status: Review Needed"
      - "Type: Dependencies"
      - "Type: Maintenance"
