version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Status: Review Needed"
      - "Type: Dependencies"
      - "Type: Maintenance"
      - "Type: CI"
      - "Type: Meta"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Status: Review Needed"
      - "Type: Dependencies"
      - "Type: Maintenance"
